# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Scheduler
spring.task.scheduling.pool.size=1

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-minutes=60

# Google OAuth Client IDs
app.google.android-client-id=${EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID}
app.google.ios-client-id=${EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID}
app.google.web-client-id=${EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID}

# Base URL for the application
app.base-url=${BASE_URL}
app.base-url-frontend=${BASE_URL_FRONTEND}
app.base-url-ip=${BASE_URL_IP}


logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.open-in-view=false
logging.level.com.example=DEBUG


gemini.api.key=${GEMINI_API_KEY}


spring.devtools.restart.enabled=false