# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Scheduler
spring.task.scheduling.pool.size=1

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-minutes=60

# Google OAuth Client IDs
app.google.android-client-id=${EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID}
app.google.ios-client-id=${EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID}
app.google.web-client-id=${EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID}

# Base URL for the application
app.base-url=${BASE_URL}
app.base-url-frontend=${BASE_URL_FRONTEND}
app.base-url-ip=${BASE_URL_IP}