spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://singular-orca-26.clerk.accounts.dev
          jwk-set-uri: https://singular-orca-26.clerk.accounts.dev/.well-known/jwks.json
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  task:
    scheduling:
      pool:
        size: 1
  devtools:
    restart:
      enabled: false



  base-url: ${BASE_URL}
  base-url-frontend: ${BASE_URL_FRONTEND}
  base-url-ip: ${BASE_URL_IP}

clerk:
  secret-key: ${CLERK_SECRET_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}

server:
  error:
    include-stacktrace: always
    include-message: always

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
    com.example.mobileApp: DEBUG
