import { StyleSheet } from "react-native";
import { COLORS, SIZES, FONTS } from "../../../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: { 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: SIZES.padding, 
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backBtn: {
    padding: 4,
    marginRight: 10,
  },
  headerTitle: { ...FONTS.h2, color: COLORS.text, fontWeight: '800' },
  content: { padding: SIZES.padding },
  section: {
    marginBottom: 20,
  },
  label: { 
    ...FONTS.body2, 
    color: COLORS.muted, 
    marginBottom: 8, 
    fontWeight: "700", 
    textTransform: "uppercase",
    fontSize: 12,
  },
  input: {
    backgroundColor: COLORS.surface, 
    borderRadius: SIZES.radius,
    paddingHorizontal: 16, 
    paddingVertical: 14,
    ...FONTS.body1, 
    color: COLORS.text,
    borderWidth: 1, 
    borderColor: COLORS.border,
  },
  textArea: { height: 120 },
  suggestionList: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 4,
    maxHeight: 200,
    zIndex: 1000,
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  suggestionText: {
    ...FONTS.body2,
    color: COLORS.text,
  },
  row: { flexDirection: "row", marginBottom: 5 },
  dateTimeRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateTimeBox: {
    flex: 1,
  },
  dateDisplay: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateDisplayText: {
    ...FONTS.body2,
    color: COLORS.text,
    fontSize: 14,
  },
  errorText: {
    color: '#ff4444',
    fontSize: 11,
    marginTop: 4,
    fontWeight: '600'
  },
  categoryScroll: {
    flexDirection: 'row',
    marginTop: 5,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: 10,
  },
  activeCategoryChip: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  categoryChipText: {
    ...FONTS.body2,
    color: COLORS.muted,
  },
  activeCategoryChipText: {
    color: '#fff',
    fontWeight: '700',
  },
  freeRow: { 
    flexDirection: "row", 
    alignItems: "center", 
    gap: 12,
  },
  freeLabel: { ...FONTS.body1, fontWeight: '600' },
  toggleTrack: { 
    width: 48, 
    height: 26, 
    borderRadius: 13, 
    justifyContent: "center", 
    paddingHorizontal: 2,
  },
  toggleThumb: { 
    width: 22, 
    height: 22, 
    borderRadius: 11, 
    backgroundColor: "#fff",
  },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255, 125, 0, 0.05)',
    padding: 15,
    borderRadius: 12,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: 'rgba(255, 125, 0, 0.2)',
  },
  noticeText: {
    ...FONTS.body2,
    color: COLORS.text,
    flex: 1,
    lineHeight: 18,
  },
  submitBtn: { 
    backgroundColor: COLORS.primary, 
    borderRadius: SIZES.radius, 
    paddingVertical: 16, 
    alignItems: "center",
    marginBottom: 40,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnText: { ...FONTS.body1, color: "#fff", fontWeight: "800", fontSize: 17 },
  submitBtnDisabled: { opacity: 0.5, shadowOpacity: 0 },
});
